// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import FileTrackerConcept from "./FileTracker/FileTrackerConcept.ts";
import PasswordAuthenticationConcept from "./PasswordAuthentication/PasswordAuthenticationConcept.ts";
import LibraryConcept from "./Library/LibraryConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import SessioningConcept from "./Sessioning/SessioningConcept.ts";
import DictionaryConcept from "./Dictionary/DictionaryConcept.ts";

export type { default as FileTrackerConcept } from "./FileTracker/FileTrackerConcept.ts";
export type { default as PasswordAuthenticationConcept } from "./PasswordAuthentication/PasswordAuthenticationConcept.ts";
export type { default as LibraryConcept } from "./Library/LibraryConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as SessioningConcept } from "./Sessioning/SessioningConcept.ts";
export type { default as DictionaryConcept } from "./Dictionary/DictionaryConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();
import { GeminiLLM } from "@utils/gemini-llm.ts";
export const llm = new GeminiLLM({
  apiKey: Deno.env.get("GEMINI_API_KEY") ?? "",
});

export const FileTracker = Engine.instrumentConcept(
  new FileTrackerConcept(db, llm),
);
export const PasswordAuthentication = Engine.instrumentConcept(
  new PasswordAuthenticationConcept(db),
);
export const Library = Engine.instrumentConcept(new LibraryConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Sessioning = Engine.instrumentConcept(new SessioningConcept(db));
export const Dictionary = Engine.instrumentConcept(new DictionaryConcept(db));
